# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm1_grasping
  joint_model_group_pose: start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm1_joint1
    - arm1_joint2
    - arm1_joint3
    - arm1_joint4
    - grip_leftjoint
    - grip_rightjoint
    - arm2_joint1
    - arm2_joint2
    - arm2_joint3
    - arm2_joint4
    - arm2_joint5
    - wheel_joint1
    - wheel_joint2
    - wheel_joint3
    - wheel_joint4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []